name: Autograding

on: [push]

jobs:
  html-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate HTML
        run: |
          sudo apt-get install tidy
          tidy -errors -quiet index.html
